name: Angular CI/CD

on:
  push:
    branches:
      - ci-cd

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Build Angular
      run: npm run build -- --configuration production

    - name: Deploy to IIS
      run: |
        Remove-Item "D:\Hemanth\iis\ci-cd\dist\ci-cd\browser\*" -Recurse -Force
        Copy-Item -Path ".\dist\ci-cd\browser\*" -Destination "D:\Hemanth\iis\ci-cd\dist\ci-cd\browser" -Recurse
