name: Angular CI/CD

on:
  push:
    branches:
      - ci-cd   # your branch name

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'   # <-- updated to Node.js v24

    - name: Install dependencies
      run: npm install

    - name: Build Angular
      run: npm run build -- --output-path=dist/ci-cd/browser

    # Deploy step will fail on cloud runner; leave commented or use self-hosted runner
    # - name: Deploy to IIS
    #   run: |
    #     Remove-Item "D:\Hemanth\Deployment\ci-cd2\dist\ci-cd\browser\*" -Recurse -Force
    #     Copy-Item -Path "dist/ci-cd/browser/*" -Destination "D:\Hemanth\Deployment\ci-cd2\dist\ci-cd\browser" -Recurse
